### ISSUE TITLE
Crashes when opening a new folder/file

### ISSUE THREAD

**Issue by Dniel97** [garoxas/NX_Game_Info#10]
Please fill in the details below to help us to find the cause of your issue and have it fixed

**Bug details**
After trying to open another folder or a file after `user.settings` was created, it just crashes without any error.

**Steps to reproduce**
1. Open a folder or file
2. Try again opening a folder or file -> Crash

**Application information**
 - OS name and version: macOS Sierra 10.12.6
 - Version: v0.5+hotfix.1
 - Application path: /Applications/
 - prod.keys path: same folder

**Debug log**
none created
**Crash log (if any)**
none created
**Other information**
When I remove `user.settings` I can open another folder or file.

**Comment by garoxas** [comment]
Can you please submit the user.settings file? And please delete entries in `NX_Game_Info.Common_x002B_History` to reduce the file size
If you want to redact your username if it's in some of directory paths, feel free to do that as long as you keep the rest of the path intact
Thanks

**Comment by Dniel97** [comment]
Here is the `user.settings` file without all `NX_Game_Info.Common_x002B_History` Tags.
[user.settings.zip](https://github.com/garoxas/NX_Game_Info/files/3419474/user.settings.zip)
I tried your new version but the same problem exists.

**Comment by garoxas** [comment]
I still can't reproduce it
Please check if there's any step that I did differently

1. Download the zip from GitHub release page
2. Extract and put it in `/Applications/`
3. Put `prod.keys` also in `/Applications/`
4. Run the app
5. Open file/directory then pick somewhere in the external hard drive (based on your user.settings it looks like you did this)
6. Works fine, `user.settings` will be created on `/Applications/`
7. Do the same thing in step 5 but it crashes

Anything different?

**Comment by Dniel97** [comment]
I went through all your steps again and exactly at step 7 it crashes. As soon as I click on `Open File` or 
`Open Directory` it crashes. Interestingly I can click on `Open SD Card` without a crash.

**Comment by garoxas** [comment]
Yeah that's because both open file and open directory use the InitialDirectory entry in user.settings but open SD uses SDCardDirectory
Can you try open another directory not in your external hard drive? The app will automatically open the last open path if there's one already, and I have suspicion that when it tries to load from external somehow it crashes

I'm gonna try it on macOS 11.12 tomorrow (I'm testing using 11.14 now) and see how it goes

**Comment by Dniel97** [comment]
Here I open a folder on my desktop but when i try to open a folder/file it still crashes.

[user.settings.zip](https://github.com/garoxas/NX_Game_Info/files/3421899/user.settings.zip)

**Comment by garoxas** [comment]
Lol yeah, macOS 10 😄 

Okay try this one https://mega.nz/#!pV8QEKKZ!wQ47dHg3H1obxrLevB8wDqBwyHvqql4oRuowO18tyNc
Feel free to reopen if you're still having issue and thanks for reporting

**Comment by Dniel97** [comment]
The new version works perfect! Thanks for fixing the bug.

Now you can create a new release 😉
