### ISSUE TITLE
Linux version would be perfect

### ISSUE THREAD

**Issue by station7** [garoxas/NX_Game_Info#11]
A linux build (for command line) is highly appreciated.

**Comment by garoxas** [comment]
Sorry even though the core of this app is built using Mono which is Linux compatible, but the UI is built using their native components for each OS. So Linux version with UI is not possible

But if you're fine with command line only, I would recommend **hactoolnet** which this app is based on https://github.com/Thealexbarney/LibHac (you can try raise issue in their GitHub for support how to run it in Linux)
If you still don't get what you want by then, feel free to reopen this issue and I'll consider implementing command line support for Linux

**Comment by station7** [comment]
Hi garoxas, 

many thanks for your reply and taking my comment seriously - I really appreciate that. I will look into hactoolnet, thanks for the hint.

**Comment by garoxas** [comment]
You're welcome

**Comment by station7** [comment]
Okay, I got hactool running on linux. All I want is to get the titleID from an xci file, but you suggest hactool**net**, right? That would require the .dotnet framework and I do not know how to use that...

**Comment by garoxas** [comment]
You need to install .NET Core from https://dotnet.microsoft.com/download
If you have trouble using that, please search on StackOverflow or other forums. I can't provide support for running .NET here

**Comment by station7** [comment]
Of course, thanks anyway!

**Comment by garoxas** [comment]
Done in [v0.7](https://github.com/garoxas/NX_Game_Info/releases/tag/v0.7)

**Comment by station7** [comment]
Many thanks, I will look into it!
