### ISSUE TITLE
Enhancement: Rename files?

### ISSUE THREAD

**Issue by station7** [garoxas/NX_Game_Info#12]
Would it be possible to let NX_Game_Info rename the files or add the title id to the filename? If  .nsp-files  include the [titleid] in  square brackets, they could be thrown onto a nut server for further deployment...

**Comment by garoxas** [comment]
No, that would be out of scope for this app
I've already mentioned this in GBAtemp that I'm limiting the number of features for this app. And among others, rename files, trim XCI up to install to Goldleaf will be the ones that will not be implemented
You may try https://github.com/gibaBR/Switch-Backup-Manager for renaming files though

**Comment by garoxas** [comment]
#22
