### ISSUE TITLE
Please Update for contents which use the latest Keyset

### ISSUE THREAD

**Issue by lookye** [garoxas/NX_Game_Info#13]
Please fill in the details below to help us to find the cause of your issue and have it fixed

**Bug details**
Opening a nsp file which uses the latest keys just leave an empty window and says, that its missing master_key_07 even if the prod.keys are from 8.1.0

**Steps to reproduce**
1. Grab latest Keys made with Lockpick_RCM on 8.1.0
2. Open the latest NX Game Info
3. Open a NSP file which needs Master Key 07 and see a empty line instead of the game details
4. 

**Application information**
 - OS name and version:
 - Version:
 - Application path:
 - prod.keys path:
 - Game filename: Turok 2 Seeds of Evil [0100CDC00D8D6000][v0].nsp
 - Game source: CDN
<img width="1438" alt="Bildschirmfoto 2019-08-14 um 15 54 22" src="https://user-images.githubusercontent.com/45557556/63026719-f6c06600-beab-11e9-8681-c6988e4afe7b.png">

**Debug log**

**Crash log (if any)**

**Other information**

**Comment by garoxas** [comment]
did you mean masterkey 7 which came on 7.0.0 or masterkey 8 which is 8.1.0?
because if it's masterkey 7, I have lots of them that are working properly. but I still don't have any using masterkey 8

**Comment by lookye** [comment]
I added the details with an example (Turok 2) + screenshot.

**Comment by lookye** [comment]
<img width="1361" alt="Bildschirmfoto 2019-08-15 um 09 55 35" src="https://user-images.githubusercontent.com/45557556/63081037-e14a4b00-bf42-11e9-85c5-a2e3db69bea3.png">
This is better I think.
Tested games are: 
PC Building Simulator [010072800CBE8000][v0].nsp
Never Give Up [01005AD00B91A000][v0].nsp
Friday the 13th The Game Ultimate Slasher Edition [010092A00C4B6000][v0].nsp
All CDN Dumps for testing purpose.

**Comment by garoxas** [comment]
Turok (and I guarantee all the other games you listed) works fine

<img width="1657" alt="nx" src="https://user-images.githubusercontent.com/11901820/63100488-61070280-bfa1-11e9-8950-f14adebd23d1.png">

If you provide all the details I asked in the issue template (Application path, prod.keys path, 
Debug log), I can help you narrow down the issue
But here some options that you can try

- Check where you put the app and see if there's another `prod.keys` in there. See if it has correct master_key_07 entry. As stated in the README, the app will look for prod.keys in 2 locations
- Recheck your master_key_07 key, it should starts with 92 and ends with 0e. If it's different then it's wrong
- This is unlikely but check your file again, Turok should be 589436681 bytes

**Comment by deadair3210** [comment]
Might try also making sure the key is all either Caps or lower case. Had a similar issue with switch backup manager

**Comment by garoxas** [comment]
mine is in lowercase, but never tried combine both lol

**Comment by deadair3210** [comment]
Mine was in whatever form the key came out of the switch in, and apparently it didn't like that. Who knew it was a language teacher lol

**Comment by lookye** [comment]
You´re right. There was an old prod.keys file in the .switch folder. After deleting it, everything works again as intended. Sorry.

**Comment by garoxas** [comment]
No problem 👍
