### ISSUE TITLE
Can't open program?

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [garoxas/NX_Game_Info#14]
When I try to run the NX Game Info.exe nothing happens. The only time I can get any reaction is when the prod.keys are missing.
Also, can you export the data from this and open it without the gui from a command line? I wanted to do a python script where I need to get the game names, title id and if its a game/dlc/update from switch games and this is the only solution I found. I don't really know how to find anything except the title id in the game files.

**Comment by LeonardFiedrowicz** [comment]
Only the latest version doesnt seem to start.

**Comment by muxi1** [comment]
The same goes for me.

**Comment by garoxas** [comment]
Please re-download from https://github.com/garoxas/NX_Game_Info/releases/tag/v0.6, and thanks for reporting

As for command line interface, it has been suggested by other as well. Can't promise when or if I can deliver it, but I will consider it
Separate issue for this has been raised in #15
