### ISSUE TITLE
NSZ Support

### ISSUE THREAD

**Issue by lookye** [garoxas/NX_Game_Info#19]
**Describe the solution you'd like**
The possibility to read nsz files for all content information the same as with nsp files.

**Comment by garoxas** [comment]
full support for nsz is not possible until LibHac has support for compressed nca files which I don't see it's being implemented soon

so as of now the best I can do is let the app to try read all info from the remaining untouched nca. it's been done for a while in https://github.com/garoxas/NX_Game_Info/commit/e5f77c3ea6cbe633c9eb1ac088c9a088112eff4b but no public release yet
