### ISSUE TITLE
™ symbol gets replaced with T in game titles in the command line interface

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [garoxas/NX_Game_Info#24]
**Bug details**
The ™ symbol in titles like Puyo Puyo™ Tetris or Starlink: Battle for Atlas™ has the ™ replaced with a T in the Title Name when using the command line.

**Steps to reproduce**
1. $ .\nxgameinfo_cli.exe -z "E:\Emulator\ROMs\Nintendo - Switch\Puyo Puyo Tetris"
2. Output:

E:\Emulator\ROMs\Nintendo - Switch\Puyo Puyo Tetris\Puyo Puyo Tetris.nsp
├ Title ID: 0100F3D001DEE000
├ Base Title ID: 0100F3D001DEE000
├ Title Name: Puyo PuyoT Tetris®
├ Display Version: 1.0.0
├ Version: 0
├ Latest Version:
├ System Update: 0
├ System Version: 0
├ Application Version:
├ Masterkey: 0 (1.0.0-2.3.0)
├ Title Key: [not sure if I should include that here]
├ Publisher: Deep Silver
├ Languages: en-US
├ Filename: E:\Emulator\ROMs\Nintendo - Switch\Puyo Puyo Tetris\Puyo Puyo Tetris.nsp
├ Filesize: 1,04 GB
├ Type: Base
├ Distribution: Digital
├ Structure: CDN
├ Signature: Passed
├ Permission: Safe
└ Error:

**Comment by LeonardFiedrowicz** [comment]
Changing to
chcp 65001
Seems to fix that, although that seem to break the |- character when writing to a file.

**Comment by garoxas** [comment]
Somewhat related, if you're having issue with command line interface not showing Japanese or Chinese characters then please follow steps here https://stackoverflow.com/a/54327996

> for some characters you need to install extra fonts (ie. Chinese).
> ![4tZU0](https://user-images.githubusercontent.com/11901820/71585944-ebb05e80-2b4a-11ea-9e2b-9a8c0397080e.png)
> 
> In Windows 10 first go to Region & language settings and install support for required language: enter image description here
> ![I2Uaq](https://user-images.githubusercontent.com/11901820/71585959-fc60d480-2b4a-11ea-8055-b3cbd52257a4.png)
> 
> After that you can go to Command Prompt Proporties (or Defaults if you like) and choose some font that supports your language (like KaiTi in Chinese case): enter image description here
> 
> Now you are set to go: 
> ![66ZdY](https://user-images.githubusercontent.com/11901820/71585969-0387e280-2b4b-11ea-9161-43f17eddbcf3.png)

**Comment by LeonardFiedrowicz** [comment]
´Thanks
