### ISSUE TITLE
Linux cli install instructions could be better

### ISSUE THREAD

**Issue by bmn001** [garoxas/NX_Game_Info#30]
**Bug details**
Linux instructions could be improved a bit

**Steps to reproduce**

Installation instructions currently say this:
```
Install .NET Core Runtime and Mono from the following links
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current
https://www.mono-project.com/download/stable/#download-lin-ubuntu
```
However, on Ubuntu 20.04 at least, you do not need to install the .net core runtime.  It will work without it.
Mono was a bit different.  If you attempt to run mono without installing it first, Ubuntu will prompt you to install mono-runtime.  Doing this will cause nx_game_info to tell you your keys are missing when they are not.
Really all you need to do to get this to run is type one line-
`sudo apt install mono-devel`

And nx_game_info will then work.

**Comment by garoxas** [comment]
I was referring to the official instructions for both .NET and Mono in the README

I'm gonna check if installing .NET is really required or not, but as for mono, although simply installing mono-devel worked on your end, I can't guarantee that it'll work with everyone. So I'm guessing it's better to leave it to the official instructions although there are extra steps that may not be necessary, but at least it works for everyone
