### ISSUE TITLE
Display/read nsz files from directories

### ISSUE THREAD

**Issue by sevenpastzeero** [garoxas/NX_Game_Info#32]
I use NX Game Info to check if my games have new updates. Recently I started moving to nsz format. But the program does not read these files when open a game folder.

**Comment by garoxas** [comment]
Yes, this program was not built with NSZ support. I've mentioned it several times already, among them was #19 
But it does support "partially", as in it can list down NSZ files and read some data but not all of them. You may want to check https://github.com/garoxas/NX_Game_Info#how-to on the Compressed NCA section

And no, I don't think I'll add full NSZ support (again see #19). Sorry

**Comment by sevenpastzeero** [comment]
> Yes, this program was not built with NSZ support. I've mentioned it several times already, among them was #19
> But it does support "partially", as in it can list down NSZ files and read some data but not all of them. You may want to check https://github.com/garoxas/NX_Game_Info#how-to on the Compressed NCA section
> 
> And no, I don't think I'll add full NSZ support (again see #19). Sorry

Thank you. I didn't want a full nzs support. I just wanted it to list the files, and the readme provided the solution. (I guess I missed that part in the readme, my bad).
Thanks again.

**Comment by garoxas** [comment]
No problem. Let me know if there's any issue
