### ISSUE TITLE
Can you read game Chinese name?

### ISSUE THREAD

**Issue by Sorata** [garoxas/NX_Game_Info#38]
For example, this nsz file, I can get detail info like: 
```
├ Title ID: 010071B017DD6800
├ Base Title ID: 010071B017DD6000
├ Title Name: There Will Be No Turkey This Christmas
├ Display Version: 1.0.1
├ Version: 65536
├ Latest Version:
├ System Update:
├ System Version: 15.0.0
├ Application Version:
├ Masterkey:
├ Title Key: 544EDE4FF050B5A83351CE57DD58AA6C
├ Publisher: Silesia Games Sp. z o.o.
├ Languages: en-US
├ Filename: C:\There Will Be No Turkey This Christmas[今年圣诞节不会有火鸡][010071B017DD6800][1.0.1][65536][15.0.0].nsz
├ Filesize: 18.95 MB
├ Type: Update
├ Distribution: Digital
├ Structure: CDN
├ Signature:
├ Permission:
└ Error: Unsupported Format: Compressed NCA
```
But there is nothing about 今年圣诞节不会有火鸡, can you please add it? I think the string 今年圣诞节不会有火鸡 is also one of the file properties.

NSZ file is here:
[There Will Be No Turkey This Christmas[今年圣诞节不会有火鸡][010071B017DD6800][1.0.1][65536][15.0.0].zip]

_---edited--- (removed copyrighted file)_

**Comment by garoxas** [comment]
![image](https://user-images.githubusercontent.com/11901820/205418503-6ee0ec7e-36af-46d8-9117-2f9ffdf9451a.png)
I don't think the file has Chinese title name in it. I've checked the file and it only has the AmericanEnglish name

Also I'd like to point out even though the game file has title name for all languages, this app will only read the first one available (usually AmericanEnglish) for the sake of simplicity

**Comment by Sorata** [comment]
Thank you very much for your reply. I get it, the program itself is good enough, thank you for what you do for us who love games.
