### ISSUE TITLE
Bug: Can´t start v5 on OSX 10.14.5

### ISSUE THREAD

**Issue by lookye** [garoxas/NX_Game_Info#7]
Please fill in the details below to help us to find the cause of your issue and have it fixed

**Bug details**
I´ve downloaded v5.
After opening it, it loads for a few seconds, then it closes itself immediately.
v41 works.

**Steps to reproduce**
1. Download v5
2. Open it

**Application information**
 - OS name and version: OSX - 10.14.5
 - Version: v5
 - Application path: Desktop
 - prod.keys path: Desktop

**Debug log**
none created

**Crash log (if any)**

**Other information**

**Comment by garoxas** [comment]
Fixed in [v0.5+hotfix.1](/garoxas/NX_Game_Info/releases/tag/v0.5%2Bhotfix.1)

**Comment by lookye** [comment]
The hotfix works. Thanks!
